version: "3.8"
services:
  saa_frontend:
    build: ./client
    ports:
      - "5173:5173"
    networks:
      - saa-app
  saa_backend:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - saa-app
networks:
  saa-app:
    driver: bridge
