version: "3.8"
services:
  saa_frontend:
    build: "./client"
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - saa-app
  saa_backend:
    build: "./server"
    ports:
      - "5000:5000"
    networks:
      - saa-app
networks:
  saa-app:
    driver: bridge
